version: "3.9"

services:
  tts-demos:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: oblivion208/tts-demo:0.1.0-gpu
    container_name: tts
    tty: true
    ipc: "host"
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    working_dir: /app
    volumes:
      - ./:/app
    command: bash
